# Generated by Django 6.0.3 on 2026-03-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_department_employee_email_employee_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_role',
            field=models.CharField(default='Employee', max_length=120),
        ),
    ]
