# Generated by Django 6.0.3 on 2026-03-23 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('transfers', '0006_transfer_approved_at_transfer_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TRANSFER_REQUEST', 'Transfer Request'), ('TRANSFER_APPROVED', 'Transfer Approved'), ('RETURN_REQUEST', 'Return Request'), ('OVERDUE', 'Overdue')], default='TRANSFER_REQUEST', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transfers.transfer'),
        ),
    ]
