# Generated by Django 6.0.3 on 2026-03-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('items', '0001_initial'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probable_days', models.IntegerField()),
                ('expected_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CONFIRMED', 'Confirmed')], db_index=True, default='PENDING', max_length=20)),
                ('is_received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_office', to='offices.office')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.employee')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.employee')),
                ('to_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_office', to='offices.office')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expected_date'], name='transfers_t_status_9bd17b_idx')],
            },
        ),
    ]
