# Generated by Django 6.0.3 on 2026-03-22 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transfer',
            name='transfers_t_status_9bd17b_idx',
        ),
        migrations.AddField(
            model_name='transfer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='serial_number',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='is_received',
        ),
    ]
