# Generated by Django 6.0.3 on 2026-03-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_remove_transfer_transfers_t_status_9bd17b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='description',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
    ]
