# Generated by Django 6.0.3 on 2026-03-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_transfer_is_received_transfer_is_returned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='is_received',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='transfer',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
