# Generated by Django 6.0.3 on 2026-03-23 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_remove_transfer_is_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='returns/')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_images', to='transfers.transfer')),
            ],
        ),
        migrations.CreateModel(
            name='TransferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transfers/')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='transfers.transfer')),
            ],
        ),
    ]
