# Generated by Django 6.0.3 on 2026-03-23 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_role'),
        ('transfers', '0005_returnimage_transferimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='return_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_confirmed_transfers', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='return_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requested_transfers', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('AWAITING_APPROVAL', 'Awaiting Approval'), ('APPROVED', 'Approved'), ('RECEIVED', 'Received'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned')], default='AWAITING_APPROVAL', max_length=30),
        ),
    ]
