# Generated by Django 6.0.3 on 2026-03-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0006_transfer_approved_at_transfer_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('AWAITING_APPROVAL', 'Awaiting Approval'), ('APPROVED', 'Approved'), ('RECEIVED', 'Received'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='AWAITING_APPROVAL', max_length=30),
        ),
    ]
