# Generated by Django 6.0.3 on 2026-03-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SIM', 'Simulator'), ('DEV', 'Device'), ('OTH', 'Other')], max_length=10),
        ),
    ]
