# Generated by Django 6.0.3 on 2026-03-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_office_floor_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='floor_choices',
            field=models.TextField(blank=True, default='', help_text='Optional custom floors or areas, separated by commas or new lines.'),
        ),
    ]
